POST http://localhost:8080/devops_starter_war_exploded/api/login

{"username":"user", "password":"test123"}

###
POST http://localhost:8080/ca2_startcode_backend_war_exploded/api/info/newuser

{"userName":"user2", "userPass":"test123"}

###
POST http://localhost:8080/ex_startcode_backend_war/api/boat/createboat

{"brand" : "1", "make" : "2", "name" : "3", "image" : "4","owners" : ["admin"], "harbourID" : "1"}

###
PUT http://localhost:8080/ex_startcode_backend_war/api/boat/1/updateboat

{"brand" : "test1", "make" : "test1", "name" : "test1", "image" : "image","owners" : ["user"], "harbourID" : "1"}

###
DELETE http://localhost:8080/ex_startcode_backend_war/api/boat/1/deleteboat

###
GET http://localhost:8080/examTest_war_exploded/api/harbour/all